name: Generate SBOM with cdxgen

on:
  workflow_call:
    inputs:
      src_repository:
        description: 'Source Repository'
        type: string
        required: true
        default: ''
      src_branch:
        description: 'Branch'
        type: string
        required: false
        default: ''
      src_type:
        description: 'Project Type (java, python, dotnet) see https://cyclonedx.github.io/cdxgen/#/PROJECT_TYPES'
        type: string
        required: false
        default: 'java'
      src_profile:
        description: BOM profile to use for generation. Default generic.
        type: string
        required: false
        default: 'generic'
  workflow_dispatch:
    inputs:
      src_repository:
        description: 'Source Repository'
        required: true
        default: ''
      src_branch:
        description: 'Branch'
        required: false
        default: ''
      src_type:
        description: 'Project Type (java, python, dotnet) see https://cyclonedx.github.io/cdxgen/#/PROJECT_TYPES'
        required: false
        default: 'java'
      src_profile:
        description: BOM profile to use for generation. Default generic.
        required: false
        type: choice
        options:
          - 'appsec'
          - 'research'
          - 'operational'
          - 'threat-modeling'
          - 'license-compliance'
          - 'generic'
          - 'machine-learning'
          - 'ml'
          - 'deep-learning'
          - 'ml-deep'
          - 'ml-tiny'
        default: 'generic'
env:
  OUTPUT_NAME: 'cyclonedxSBOM'
jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.src_repository }}
        ref: ${{ inputs.src_branch }}

    - name: Generate SBOM using cdxgen container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app:rw \
          -v /tmp:/tmp \
          -t ghcr.io/cyclonedx/cdxgen:latest \
          -r /app -o /app/bom.json -t ${{ inputs.src_type }} \
          --profile ${{ inputs.src_profile }} --json-pretty

    - name: Upload SBOM results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.OUTPUT_NAME }}-${{ inputs.src_profile }}
        path: ${{github.workspace}}/bom.json 
